import { AuthInitializer } from '@/components/AuthInitializer';
import type { Metadata } from 'next';
import { ABeeZee } from 'next/font/google';
import './globals.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin'],
// });

const aBeeZee = ABeeZee({
	weight: '400',
	variable: '--font-aBeeZee',
	subsets: ['latin'],
	fallback: ['sans-serif'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${aBeeZee.variable}  antialiased`}>
				{children}
				<AuthInitializer />
			</body>
		</html>
	);
}

// ${geistMono.variable}
